---
openapi: "3.0.0"
info:
  version: 1.0.0
  title: FibNum
  license:
    name: MIT
servers:
- url: http://localhost:8080
  description: Local server
paths:
  /fib/{fibNum}:
    get:
      summary: get ntf fib num
      operationId: getFibNum
      parameters:
        - name: fibNum
          in: path
          required: true
          description: nth fib num
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FibNum"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    FibNum:
      type: object
      required:
        - num
      properties:
        num:
          type: integer
          format: int64
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
